num1 =input('Enter your first number : ')
num2 =input('Enter your second number : ')
num3 =input('Enter your third number : ')
num4 =input('Enter your fourth number : ')
num5 =input('Enter your fifth number : ')
af = float(num1)
ac = complex(num1)
print('float of',num1,'Equal',af)
print('complex of',num1,'Equal',ac)
bf = float(num2)
bc = complex(num2)
print('float of',num2,'Equal',bf)
print('complex of',num2,'Equal',bc)
cf = float(num3)
cc = complex(num3)
print('float of',num3,'Equal',cf)
print('complex of',num3,'Equal',cc)
df = float(num4)
dc = complex(num4)
print('float of',num4,'Equal',df)
print('complex of',num4,'Equal',dc)
ef = float(num5)
ec = complex(num5)
print('float of',num5,'Equal',ef)
print('complex of',num5,'Equal',ec)
