print('+'*25)
print('โปรแกรมหยิบสินค้าใส่ตะกร้า')
print('+'*25)
goods = []
goods.append(input('หยิบสินค้าชิ้นที่ 1 : '))
goods.append(input('หยิบสินค้าชิ้นที่ 2 : '))
goods.append(input('หยิบสินค้าชิ้นที่ 3 : '))
goods.append(input('หยิบสินค้าชิ้นที่ 4 : '))
goods.append(input('หยิบสินค้าชิ้นที่ 5 : '))
print('+'*25)
print('สินค้าที่หยิบลงตะกร้ามีดังนี้')
print('+'*25)
print('ชิ้นที่ 1 :',goods[0])
print('ชิ้นที่ 2 :',goods[1])
print('ชิ้นที่ 3 :',goods[2])
print('ชิ้นที่ 4 :',goods[3])
print('ชิ้นที่ 5 :',goods[4])